config/routes.rb
Rails.application.routes.draw do
  post '/webliographyentries/post_to_api' => 'webliographyentries#post_to_api'
  resources :messages
  resources :students
  resources :courses do
    resources :assignments
  end
  resources :courses do
    resources :lessons
  end
  resources :courses do
    resources :lightbulbs
  end
  resources :assignments do
    resources :submissions
  end
  resources :teachers
  resources :enrollments
  resources :favorites
  get '/courses/:id/summaries' => 'courses#summaries', as: 'summaries'
  get '/courses/:id/useful_links' => 'courses#useful_links', as: 'useful_links'
  get 'courses/:course_id/lesson/:id' => 'lessons#show'
  # get '/student/sign_up' => 'devise/registrations#new'
  get '/lightbulbs' => 'lightbulbs#create', as: "lightbulbs"
  post '/lightbulbs' => 'lightbulbs#new', as: "new_lightbulb"
  # post '/courses/:id' => 'courses#search_classmates', as: 'search_classmates'
  post '/courses/:id/send_lightbulb' => 'courses#send_lightbulb', as: 'send_lightbulb'
  post '/courses/:id' => 'courses#search_classmates', as: 'search_classmates'
  post '/courses/:id/topicsearch' => 'courses#search', as: 'search_assignments'
  get '/student_dashboard' => 'student_dashboard#index'
  get '/teacher_dashboard' => 'teacher_dashboard#index'
  get  '/login', to: 'sessions#new',    as: 'new_login'
  get  '/teacher_login', to: 'sessions#new_teacher_session',    as: 'teacher_login'
  post '/login', to: 'sessions#create', as: 'create_session' #username, pw params passed in
  post '/login', to: 'sessions#create_teacher_session', as: 'create_teacher_session' #username, pw params passed in
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/about', to: 'application#about', as: 'about'
  root 'application#homepage'
end

app/models/lightbulb.rb
class Lightbulb < ActiveRecord::Base
  belongs_to :enrollment
  belongs_to :student
  belongs_to :assignment
  belongs_to :submission #check if needed
  belongs_to :course
  belongs_to :lesson
  has_many :favorites
end

app/controllers/lightbulbs_controller.rb
class LightbulbsController < ApplicationController
  before_action :set_lightbulb, only: [:show, :edit, :update, :destroy]

  # GET /lightbulbs
  # GET /lightbulbs.json
  def index
    @lightbulbs = Lightbulb.all
  end

  # GET /lightbulbs/1
  # GET /lightbulbs/1.json
  def show
  end

  # GET /lightbulbs/new
  def new
    #new lightbulb
  end
  # GET /lightbulbs/1/edit
  def edit
  end

  # POST /lightbulbs
  # POST /lightbulbs.json
  def create
  end


  # PATCH/PUT /lightbulbs/1
  # PATCH/PUT /lightbulbs/1.json
  def update
    respond_to do |format|
      if @lightbulb.update(lightbulb_params)
        format.html { redirect_to @lightbulb, notice: 'Lightbulb was successfully updated.' }
        format.json { render :show, status: :ok, location: @lightbulb }
      else
        format.html { render :edit }
        format.json { render json: @lightbulb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lightbulbs/1
  # DELETE /lightbulbs/1.json
  def destroy
    @lightbulb.destroy
    respond_to do |format|
      format.html { redirect_to lightbulbs_url, notice: 'Lightbulb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lightbulb
      @lightbulb = Lightbulb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lightbulb_params
      params.require(:lightbulb).permit(:assignment_id, :course_id, :student_id, :lesson_id, :summary, :video_url, :article_url, :other)
    end
end

app/helpers/lightbulbs_helper.rb
module LightbulbsHelper
end

app/views/lightbulbs/_form.html.erb
<%= form_for(@lightbulb) do |f| %>
  <% if @lightbulb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lightbulb.errors.count, "error") %> prohibited this lightbulb from being saved:</h2>

      <ul>
      <% @lightbulb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :article_url %><br>
    <%= f.text_field :article_url %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.text_field :other %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lightbulbs/edit.html.erb
<h1>Editing Lightbulb</h1>

<%= render 'form' %>

<%= link_to 'Show', @lightbulb %> |
<%= link_to 'Back', lightbulbs_path %>

app/views/lightbulbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lightbulbs</h1>

<table>
  <thead>
    <tr>
      <th>Summary</th>
      <th>Video url</th>
      <th>Article url</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lightbulbs.each do |lightbulb| %>
      <tr>
        <td><%= lightbulb.summary %></td>
        <td><%= lightbulb.video_url %></td>
        <td><%= lightbulb.article_url %></td>
        <td><%= lightbulb.other %></td>
        <td><%= link_to 'Show', lightbulb %></td>
        <td><%= link_to 'Edit', edit_lightbulb_path(lightbulb) %></td>
        <td><%= link_to 'Destroy', lightbulb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lightbulb', new_lightbulb_path %>

app/views/lightbulbs/new.html.erb
<h1>New Lightbulb</h1>

<%= render 'form' %>

<%= link_to 'Back', lightbulbs_path %>

app/views/lightbulbs/show.html.erb
  <strong>Summary:</strong>
  <%= @lightbulb.summary %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @lightbulb.video_url %>
</p>

<p>
  <strong>Article url:</strong>
  <%= @lightbulb.article_url %>
</p>

<p>
  <strong>Other:</strong>
  <%= @lightbulb.other %>
</p>

<%= link_to 'Edit', edit_lightbulb_path(@lightbulb) %> |
<%= link_to 'Back', lightbulbs_path %>