config/routes.rb
Rails.application.routes.draw do
  post '/webliographyentries/post_to_api' => 'webliographyentries#post_to_api'
  resources :messages
  resources :students
  resources :courses do
    resources :assignments
  end
  resources :courses do
    resources :lessons
  end
  resources :courses do
    resources :lightbulbs
  end
  resources :assignments do
    resources :submissions
  end
  resources :teachers
  resources :enrollments
  resources :favorites
  get '/courses/:id/summaries' => 'courses#summaries', as: 'summaries'
  get '/courses/:id/useful_links' => 'courses#useful_links', as: 'useful_links'
  get 'courses/:course_id/lesson/:id' => 'lessons#show'
  # get '/student/sign_up' => 'devise/registrations#new'
  get '/lightbulbs' => 'lightbulbs#create', as: "lightbulbs"
  post '/lightbulbs' => 'lightbulbs#new', as: "new_lightbulb"
  # post '/courses/:id' => 'courses#search_classmates', as: 'search_classmates'
  post '/courses/:id/send_lightbulb' => 'courses#send_lightbulb', as: 'send_lightbulb'
  post '/courses/:id' => 'courses#search_classmates', as: 'search_classmates'
  post '/courses/:id/topicsearch' => 'courses#search', as: 'search_assignments'
  get '/student_dashboard' => 'student_dashboard#index'
  get '/teacher_dashboard' => 'teacher_dashboard#index'
  get  '/login', to: 'sessions#new',    as: 'new_login'
  get  '/teacher_login', to: 'sessions#new_teacher_session',    as: 'teacher_login'
  post '/login', to: 'sessions#create', as: 'create_session' #username, pw params passed in
  post '/login', to: 'sessions#create_teacher_session', as: 'create_teacher_session' #username, pw params passed in
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/about', to: 'application#about', as: 'about'
  root 'application#homepage'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:send_lightbulb, :search, :show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json

  def useful_links
    conf = LearningStudioAuthentication::Config::OAuthConfig.new({
        :application_id   => 'c5b8742f-c459-4fc2-91a1-7ee542acb214',
        :application_name => 'Lightpath',
        :client_string    => 'gbtestc',
        :consumer_key     => '4d2b474e-7b70-4b7e-aff5-7313567c2c38',
        :consumer_secret  =>  'DmyLEZn8ts7MuOUm'
    })
    oauth_factory = LearningStudioAuthentication::Service::OAuthServiceFactory.new(conf)
    service = LearningStudioCore::BasicService.new(oauth_factory)
    service.use_oauth2('anisha.srivastava123.student@gmail.com','msuTooEg')
    response = service.request("GET","/courses/12288063/webliographyEntries")
    @useful_response = JSON.parse(response.content)
    @titles = @useful_response["webliographyEntries"].map do |entry|
                entry['title']
              end
    @stop = @titles.count-1.to_i
    @titles = @titles[10..@stop]
    @urls = @useful_response["webliographyEntries"].map do |entry|
                entry['site']['url']
              end
    @submitters = @useful_response["webliographyEntries"].map do |entry|
                entry['submitter']['firstName']
              end
    render 'useful_links'
  end

  def search
    #get assignments for the course page user is on
    @q = "%#{params[:query]}%".downcase.strip
    @lessons = Lesson.where("lower(title) LIKE ?", @q)
    @results = @lessons
    # @results += Lightbulb.where("lower(summary) || lower(video_url) LIKE ?", @q)
    @results
    @bulbs = current_user.lightbulbs.where(course_id: @course.id)
    render 'show'
  end

  def summaries #collecting summaries for review sheet page
    @course = Course.find(params[:id])
    @lightbulbs = Lightbulb.where(course_id: @course.id)
    @summarylightbulbs = Array.new
    @lightbulbs.each do |lightbulb|
      @summarylightbulbs.push(lightbulb) if lightbulb.summary.present?
    end
    # @summaries = @lightbulbs.map do |lightbulb|
    #   lightbulb.summary if lightbulb.summary.present?
    render 'summaries'
  end

  def send_lightbulb #searching DB for recipient name
    @subject = "%#{params[:querysubject]}%".downcase.strip
    @qu = "%#{params[:queryclassmates]}%".downcase.strip
    @recipient = Student.find_by("lower(first_name) LIKE ?", @qu)
    @bulbs= current_user.lightbulbs.where(course_id: @course.id)
    render 'show'
    #Use on modal
  end
# Started working when I changed .where to .find_by
  def index
    @assignments
    @courses = Course.all
  end

  def show #Need to use ENV variables
    # @course = Course.fetch(params[:id])
    # @assignments = @course.assignments
    conf = LearningStudioAuthentication::Config::OAuthConfig.new({
        :application_id   => 'c5b8742f-c459-4fc2-91a1-7ee542acb214',
        :application_name => 'Lightpath',
        :client_string    => 'gbtestc',
        :consumer_key     => '4d2b474e-7b70-4b7e-aff5-7313567c2c38',
        :consumer_secret  =>  'DmyLEZn8ts7MuOUm'
    })
    oauth_factory = LearningStudioAuthentication::Service::OAuthServiceFactory.new(conf)
    service = LearningStudioCore::BasicService.new(oauth_factory)
    service.use_oauth2('anisha.srivastava123.student@gmail.com','msuTooEg')
    service.data_format = LearningStudioCore::BasicService::DataFormat::JSON
    @courses = service.request("GET","/me/courses?expand=course")
    @course_title = JSON.parse(@courses.content)["courses"].first.first.last.first["course"]["displayCourseCode"]
    @course = Course.find(1)
    # ("name LIKE ?", @course_title)
    @lessons = @course.lessons
    @response_array = service.request("GET","/courses/12288063/webliographyEntries")
    response = JSON.parse(@response_array.content)["webliographyEntries"]
    response = response.sort_by{|response|response["title"]}
    @lightbulbs = Array.new
    response.each do |response|
        @lightbulbs.push(response["title"], response["description"], response["url"], response["submitter"]["firstName"])
      end
    @bulbs = Array.new
    @bulbs= current_user.lightbulbs.where(course_id: @course.id)
    @recipient = Student.find_by("lower(first_name) LIKE ?", @qu)
  end

  # GET /courses/1
  # GET /courses/1.json

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      conf = LearningStudioAuthentication::Config::OAuthConfig.new({
          :application_id   => 'c5b8742f-c459-4fc2-91a1-7ee542acb214',
          :application_name => 'Lightpath',
          :client_string    => 'gbtestc',
          :consumer_key     => '4d2b474e-7b70-4b7e-aff5-7313567c2c38',
          :consumer_secret  =>  'DmyLEZn8ts7MuOUm'
      })
      oauth_factory = LearningStudioAuthentication::Service::OAuthServiceFactory.new(conf)
      service = LearningStudioCore::BasicService.new(oauth_factory)
      service.use_oauth2('anisha.srivastava123.student@gmail.com','msuTooEg')
      service.data_format = LearningStudioCore::BasicService::DataFormat::JSON
      # @currentuser = service.request("GET", "/users/38619307")
      # @current_user_firstName = JSON.parse(@currentuser.content)["users"].first["firstName"]
      # @current_user = Student.find_by("first_name LIKE ?", @current_user_firstName)
      @courses = service.request("GET","/me/courses?expand=course")
      @course_title = JSON.parse(@courses.content)["courses"].first.first.last.first["course"]["displayCourseCode"]
      @course = Course.find(1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :teacher_id, :description)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.number_field :teacher_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Teacher</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.teacher.first_name + " " + course.teacher.last_name %></td>
        <td><%= course.description %></td>
        <td><%= link_to 'Join', course %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<div class='row'>
    <div class="col s3 card-panel teal" id="courses">
      <div class="col s12 m4 l11">
        <h3><%=@course.name%></h3>
    <div id='cssmenu'>
      <ul>
        <li class='last'><a href='/student_dashboard'><p>Dashboard</p></a></li>
        <li class='has-sub'><a href='/courses/:course_id/lessons'><p>Lessons</p></a>
           <ul>
             <li><p><%= link_to "View All Lessons", course_lessons_path(@course)%></p></li>
             <li><a href='/courses/:id/lessons/1'><p><%=Lesson.find(1).title%></p></a></li>
             <li><a href='/courses/:id/lessons/2'><p><%=Lesson.find(2).title%></p></a></li>
             <li><a href='/courses/:id/lessons/3'><p><%=Lesson.find(3).title%></p></a></li>
             <li><a href='/courses/:id/lessons/4'><p><%=Lesson.find(4).title%></p></a></li>
             <li><a href='/courses/:id/lessons/5'><p><%=Lesson.find(5).title%></p></a></li>
             <li><a href='/courses/:id/lessons/6'><p><%=Lesson.find(6).title%></p></a></li>
             <li><a href='/courses/:id/lessons/7'><p><%=Lesson.find(7).title%></p></a></li>
             <li><a href='/courses/:id/lessons/8'><p><%=Lesson.find(8).title%></p></a></li>
             <li><a href='/courses/:id/lessons/9'><p><%=Lesson.find(9).title%></p></a></li>
             <li><a href='/courses/:id/lessons/10'><p><%=Lesson.find(10).title%></p></a></li>
             <li><a href='/courses/:id/lessons/11'><p><%=Lesson.find(11).title%></p></a></li>
             <li><a href='/courses/:id/lessons/12'><p><%=Lesson.find(12).title%></p></a></li>
           </ul>
        </li>
         <!-- <li class='has-sub'><a href='/courses/:id/assignments'><p>Assignments</p></a>
            <ul>
              <li><p><%= link_to "View All Assignments", course_assignments_path(@course)%></p></li>
              <%@course.assignments.each do |assignment|%>
               <li><a href='#'><p><%=assignment.title%></p></a></li>
               <%end%>
            </ul>
         </li> -->
         <!-- <li class='has-sub'><a href='#'><p>Quizzes</p></a>
            <ul>
               <li><a href='#'><span><%=@course.assignments.first.title%></span></a></li>
            </ul>
         </li> -->
         <li class='has-sub'><a href='/favorites'><p>Favorited Lightbulbs</p></a>
            <ul>
              <li><p><%= link_to "View All Favorited Lightbulbs", favorites_path(@course)%></p></li>
            </ul>
         </li>
         <li class='has-sub'><a href='/courses/:id/summaries'><p>Concept Summaries</p></a>
            <ul>
              <li><p><%= link_to "View All Concept Summaries for Lightbulb Moments", summaries_path%></p></li>
            </ul>
         </li>
         <li class='has-sub'><a href='/courses/:id/useful_links'><p>Useful Web Links</p></a>
            <ul>
              <li><p><%= link_to "View All Video & Article Links for Lightbulb Moments", useful_links_path%></p></li>
            </ul>
         </li>
         <li class='last'><a href='/student_dashboard'><p>Logout</p></a></li>
      </ul>
    </div>
  </div>
</div>
  <div class="col s6">
    <h5>Course Information</h5>
    <p><strong>Teacher:</strong>
    <%=@course.teacher.first_name + " " + @course.teacher.last_name%>
    </p>
    <p>
    <strong>Description:</strong>
    <%= @course.description %>
    </p>
    <div class='searchbar'>
      <%= form_tag search_assignments_path do %>
        <input class="search full width" id="searchbar" name="query" placeholder = "Enter a lesson to search through classmates' lightbulb moments!"
        autocomplete:"on" />
        <%if @results%>
        <% if @results.length > 0 %>
            <% @results.each do |result| %>
              <% if result.course_id == 1%>
                <div class="card-panel teal" id = "result">
                      <!-- <strong><h6><%= "Assignment:" + " " +result.title if result.has_attribute?('lesson_id')%></h6></strong> -->
                      <h6><%= "Lesson:" + " " + result.number.to_s + " " +result.title if result.has_attribute?('title')%></h6>
                      <h6><%= "Lightbulb:" + " " + result.summary + " "  if result.has_attribute?('summary')%></h6>
                      <h6>Lightbulbs:</h6>
                      <% result.lightbulbs.each do |lightbulb|%>
                      <img src ='http://s13.postimg.org/6n2pzw1zb/image.png'id = 'resultbulb'></img>
                      <%=react_component "FavoriteButton", studentID:current_user.id, lightbulbID: lightbulb.id%>
                        <p><%= lightbulb.summary if lightbulb.summary.present?%></p>
                        <p><%= link_to lightbulb.video_url, '#{lightbulb.video_url}' if lightbulb.video_url.present?%></p>
                        <p><%= link_to lightbulb.article_url, '#{lightbulb.articule_url}' if lightbulb.article_url.present?%></p>
                        <p> - <%= lightbulb.student.first_name%></p>
                      <% end %>
                </div>
              <%else%>
                <div class="card-panel teal" id='error'>
                  <%="Sorry your search is relevant for a different course. Check out another course from your dashboard!"%>
                </div>
                <% end %>
            <% end %>
        <%else%>
            <div class="card-panel teal" id='error'>
              <%="Sorry no lightbulbs can be found based on your search!"%>
            </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  </div>
  <div class="col s3" id = "side">
    <h6>Lightbulb Moments</h6>
    <%@bulbs.each do |lightbulb|%>
        <div class="row card-panel teal" id = "lightbulbmomentcard">
          <div class="col s12" id = "side">
            <div class="col s3">
          <img src ='http://s13.postimg.org/6n2pzw1zb/image.png'></img>
          </div>
          <div class="col s9">
            <div class='buttonwrapper'>
            <%=lightbulb.summary if lightbulb.summary.present?%>
            <%=link_to lightbulb.video_url, '#{article_url}' if lightbulb.video_url.present?%>
            <%=link_to lightbulb.article_url, '#{article_url}' if lightbulb.article_url.present?%>
            <a href= "#modal-<%=lightbulb.id%>" class="modal-trigger btn" id="sharebutton">Share</a>
          </div>
        </div>
        </div>
        </div>
        <div id="modal-<%=lightbulb.id%>" class="modal">
          <div class="modal-content">
            <%=react_component 'ShareLightbulbForm', lightbulbID:lightbulb.id, courseID: @course.id, senderID: current_user.id%>
            <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
         </div>
          <div class="modal-footer">
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/courses/summaries.html.erb
<%@summarylightbulbs.each do |lightbulb|%>
  <h6><%=lightbulb.lesson.title%></h6>
  <center>
  <div class="card-panel teal" id = "summary">
    <img src ='http://s13.postimg.org/6n2pzw1zb/image.png'id = 'resultbulb'></img>
  <p><%=lightbulb.summary%></p>
  </div>
  </center>
<%end%>

app/views/courses/useful_links.erb
<p><%=@titles%></p>
<p><%=@urls%></p>
<p><%=@submitters%></p>

app/views/courses/useful_links.html.erb
<p><%= link_to "Back to Course", course_path(Course.first)%></p>

<div class = 'useful_links'>
      <table class='highlight bordered centered'>
        <thead>
          <tr>
              <th data-field="">Lesson</th>
              <th data-field="">Weblink</th>
              <th data-field="">Submmitter</th>
          </tr>
        </thead>
        <tbody>
          <% @titles.each_with_index do |title, index| %>
           <tr>
             <td><%=title%></td>
             <td><%= @urls[index] %></td>
             <td><%= @submitters[index] %></td>
           </tr>
          <% end %>
        </tbody>
      </table>
</div>

<!-- <%@urls.each do |url|%>
  <p><%=url%></p>
<%end%>
<%@submitters.each do |submitter|%>
<p><%=submitter%></p>
<%end%> -->